spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root